version: "3.8"

services:
  postgres:
    image: timescale/timescaledb:2.14.2-pg15
    container_name: auditlog_postgres
    restart: always
    environment:
      POSTGRES_USER: auditlog_user
      POSTGRES_PASSWORD: auditlog_pass
      POSTGRES_DB: auditlog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auditlog_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: auditlog_opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"

  kibana:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: auditlog_kibana
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'

volumes:
  postgres_data:
  opensearch_data:
